
title: My Resume
url: 'http://tuanhtran99.github.io'
baseurl: "" #change it according to your repository name



# Profile information
yourname: Tran Tu Anh  ## put your name
yourname2: 陳秀映  ## put your name
yourname3: May  ## put your name
title: Sales and Marketing specialist  ## your title
location: Taipei, Taiwan

## Duc test
## Social Profiles
facebook: https://www.facebook.com/tran.tuanh.18041/  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/tu-anh-may-tran  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
